'use client'

// Config
import { APP_NAME } from '@/config/site'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// React
import Image from 'next/image'
import { useRouter } from 'next/router'
// MUI
import Button from '@mui/material/Button'
import CardActionArea from '@mui/material/CardActionArea'
import CardContent from '@mui/material/CardContent'
import Divider from '@mui/material/Divider'
import Grid from '@mui/material/Unstable_Grid2'
import Typography from '@mui/material/Typography'
// Components
import Card from '@/components/Card'
import Layout from '@/components/Layout'
// Types
import type { ReactElement } from 'react'
import type { NextPageWithLayout } from '@/pages/_app'

const Home: NextPageWithLayout = () => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={2}>
        <Grid xs={12} sx={{ mb: 2 }}>
          <Image
            src="/akitainuswap.png"
            alt="Akita Inu"
            layout="responsive"
            width={800}
            height={500}
          />
        </Grid>

        <Grid xs={12} sx={{ mb: 3 }}>
          <Typography
            component="h4"
            variant="h4"
            sx={{ mb: 3, fontWeight: 'bold', textAlign: 'center' }}
          >
            About
          </Typography>
          <Typography component="p" variant="body1" sx={{ color: '#2b2b2b' }}>
            Welcome to AkitaInuSwap. Here, AkitaInu is committed to operating
            our decentralized exchange with reliability and integrity. Join us
            for a seamless trading experience, where you have complete control
            over your financial transactions in a secure and trustless
            environment.
          </Typography>
        </Grid>

        <Grid xs={12} sx={{ mb: 3 }}>
          <Divider />
        </Grid>

        <Grid xs={12}>
          <Typography
            component="h4"
            variant="h4"
            sx={{ mb: 2, fontWeight: 'bold', textAlign: 'center' }}
          >
            Discover the Ecosystem
          </Typography>
        </Grid>

        <Grid xs={6}>
          <Card>
            <CardActionArea onClick={() => router.push('/swap')}>
              <CardContent>
                <Typography
                  component="h5"
                  variant="h5"
                  sx={{ mb: 1 }}
                >
                  Swap
                </Typography>
                <Typography>
                  Exchange one type of token for another quickly and securely on
                  the XRPL.
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
        </Grid>

        <Grid xs={6}>
          <Card>
            <CardActionArea onClick={() => router.push('/liquidity')}>
              <CardContent>
                <Typography
                  component="h5"
                  variant="h5"
                  sx={{ mb: 1 }}
                >
                  Liquidity
                </Typography>
                <Typography>
                  Add or remove liquidity for XRPL pools here. Select a token
                  pair, input amounts, and confirm to earn fees.
                </Typography>
              </CardContent>
            </CardActionArea>
          </Card>
        </Grid>

        <Grid xs={12} sx={{ my: 3 }}>
          <Divider />
        </Grid>

        <Grid xs={12}>
          <Typography
            component="h4"
            variant="h4"
            sx={{ mb: 2, fontWeight: 'bold', textAlign: 'center' }}
          >
            Tokenomics
          </Typography>
        </Grid>

        <Grid xs={6}>
          <Typography component="p" variant="body1" sx={{ color: '#2b2b2b' }}>
            Comming soon...
          </Typography>
        </Grid>

        <Grid xs={6}>
          <Image
            src="/akitainu1.png"
            alt="Akita Inu"
            layout="responsive"
            width={250}
            height={250}
          />
        </Grid>

        <Grid xs={12} sx={{ my: 3 }}>
          <Divider />
        </Grid>

        <Grid xs={12}>
          <Typography
            component="h4"
            variant="h4"
            sx={{ mb: 2, fontWeight: 'bold', textAlign: 'center' }}
          >
            Roadmap
          </Typography>
        </Grid>

        <Grid xs={6}>
          <Typography component="p" variant="body1" sx={{ color: '#2b2b2b' }}>
            Comming soon...
          </Typography>
        </Grid>

        <Grid xs={6} sx={{ mb: 8 }}>
          <Image
            src="/akitainu2.png"
            alt="Akita Inu"
            layout="responsive"
            width={250}
            height={250}
          />
        </Grid>
      </Grid>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default Home
